dist: trusty
sudo: false
addons:
  apt:
    packages:
    - libgeos-3.4.2
language: ruby
rvm:
  - 2.5.1
  - 2.4.4
  - 2.3.7
  - jruby-9.1.9.0
before_install: "gem update --system" # https://github.com/travis-ci/travis-ci/issues/8974
