dist: trusty
sudo: false
addons:
  apt:
    packages:
    - libgeos-3.4.2
language: ruby
rvm:
  - 2.6.0
  - 2.5.3
  - 2.4.5
  - 2.3.8
  - jruby-9.1.9.0
before_install: "gem update --system" # https://github.com/travis-ci/travis-ci/issues/8974
